name: Homebase
description: Professional DAO tooling.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.6
  syncfusion_flutter_charts: ^24.1.41
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  riverpod: ^2.5.1
  image: ^4.1.3
  qr_flutter: ^4.1.0
  toggle_switch: ^2.1.0
  url_launcher: ^6.2.5
  file_picker: ^6.1.1
  csv: ^5.1.1
  graphite: ^0.3.0
  lottie: ^3.0.0
  shared_preferences: ^2.2.2
  flutter_web3: ^2.1.6
  cached_network_image: ^3.3.1
  flutter_web3_provider: ^1.0.6
  web3dart: ^2.7.0               # requires http ≥1.1.0
  cloud_firestore: ^4.15.5
  provider: ^6.1.2
  flutter_markdown: ^0.6.18
  emojis: ^0.9.9
  animated_text_kit: ^4.2.2
  http: ^1.4.0                  # satisfies google_fonts & eip1559/http
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.1.0          # depends on http ≥1.0.0
  firebase_core: ^2.28.0
  scrollable_positioned_list: ^0.3.8
  universal_html: ^2.2.4
  gojs: ^2.0.0
  dio: ^5.4.1
  pointycastle: ^3.7.4
  go_router: ^13.1.0
  webview_flutter: ^4.1.4       # replaces webviewx

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/vectors/
    - assets/

  fonts:
    - family: CascadiaCode
      fonts:
        - asset: fonts/CascadiaCode.ttf
    - family: CascadiaMono
      fonts:
        - asset: fonts/CascadiaMono.ttf
