name: Homebase
description: Professional DAO tooling.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  cupertino_icons: ^1.0.2
  syncfusion_flutter_charts: ^22.2.9
  flutter_riverpod:
  hooks_riverpod:
  flutter_circle_chart: ^1.0.0
  beamer: 
  intl:
  riverpod:
  image: ^3.0.2
  qr_flutter:
  toggle_switch: ^2.1.0
  url_launcher:
  file_picker: ^5.2.2
  csv: ^5.0.0
  graphite: ^0.3.0
  # metamask: ^0.0.2
  lottie:
  shared_preferences: 
  # walletconnect_dart:
  flutter_web3: ^2.1.6
  flutter_gif:
  cached_network_image:
  flutter_web3_provider: ^1.0.6
  web3dart: ^2.0.0
  cloud_firestore: ^4.13.6
  provider:
  flutter_markdown: ^0.6.10
  emojis: ^0.9.9
  animated_text_kit: ^4.1.1
  http:
  flutter_vector_icons: ^1.0.0
  google_fonts: 
  firebase_core: 
  # firebase_firestore:
  scrollable_positioned_list: ^0.2.2
  universal_html: ^2.0.8
  gojs: ^2.0.0
  dio:
  webviewx: ^0.2.1
  ext_video_player: 
  youtube_player_iframe: 
  pointycastle:
  go_router: ^12.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/vectors/
    - assets/

  fonts:
    - family: CascadiaCode
      fonts:
        - asset: fonts/CascadiaCode.ttf
    - family: CascadiaMono
      fonts:
        - asset: fonts/CascadiaMono.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
