// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqvj7uTsnxX8B-PNRaNI_bWoUevyx-TII',
    appId: '1:377420069232:web:4d2b785464d3a0e09077b5',
    messagingSenderId: '377420069232',
    projectId: 'homebase-6907d',
    authDomain: 'homebase-6907d.firebaseapp.com',
    storageBucket: 'homebase-6907d.appspot.com',
    measurementId: 'G-67HZK5DL97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO48GkZ5Isa6xRPqNY1uVlLbGodnZs3NQ',
    appId: '1:377420069232:android:dd26c7fc25af185b9077b5',
    messagingSenderId: '377420069232',
    projectId: 'homebase-6907d',
    storageBucket: 'homebase-6907d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEaJWVjDgFuojZaCyoJ-JzVFZuAaISuKE',
    appId: '1:377420069232:ios:9c914d4bc0835f929077b5',
    messagingSenderId: '377420069232',
    projectId: 'homebase-6907d',
    storageBucket: 'homebase-6907d.appspot.com',
    iosBundleId: 'com.example.homebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEaJWVjDgFuojZaCyoJ-JzVFZuAaISuKE',
    appId: '1:377420069232:ios:9c914d4bc0835f929077b5',
    messagingSenderId: '377420069232',
    projectId: 'homebase-6907d',
    storageBucket: 'homebase-6907d.appspot.com',
    iosBundleId: 'com.example.homebase',
  );
}
